version: '3.4'
services:
  app:
    build:
      context: .
      target: "release"
    ports:
      - 80:3000
    depends_on:
      - postgres
    environment:
      - RACK_ENV=production
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
      - DATABASE_URL=postgres://postgres:app@postgres/app
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - ./db/sql:/db/sql
    ports:
      - "5432"
